# Generated by Django 4.2.6 on 2023-10-14 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_category_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('product_slug', models.SlugField(max_length=200, unique=True)),
                ('product_sku', models.CharField(max_length=25, unique=True)),
                ('product_description', models.CharField(blank=True, max_length=500)),
                ('product_price', models.IntegerField()),
                ('product_images', models.ImageField(blank=True, upload_to='images/products')),
                ('product_stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
