# Generated by Django 4.2.6 on 2023-10-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productvariation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariation',
            new_name='ProductOptions',
        ),
        migrations.RenameField(
            model_name='productoptions',
            old_name='product_variation_category',
            new_name='product_option_category',
        ),
        migrations.RenameField(
            model_name='productoptions',
            old_name='product_variation_value',
            new_name='product_option_value',
        ),
    ]
