# Generated by Django 4.2.6 on 2023-10-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_productvariation_productoptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOptionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_code', models.CharField(max_length=50, unique=True)),
                ('option_title', models.CharField(max_length=100)),
                ('option_title_frontend', models.CharField(max_length=100)),
                ('option_type', models.CharField(choices=[('dropdown', 'dropdown')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product option title',
                'verbose_name_plural': 'product option title',
            },
        ),
        migrations.AlterModelOptions(
            name='productoptions',
            options={'verbose_name': 'product option', 'verbose_name_plural': 'product options'},
        ),
        migrations.AlterField(
            model_name='productoptions',
            name='product_option_category',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
