# Generated by Django 4.2.6 on 2023-10-23 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_product_option_category_productoptions_product_option_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptions',
            name='product_option_titles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productoptiontitle'),
        ),
    ]
