# Generated by Django 4.2.6 on 2023-10-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_productoptions_product_option_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptiontitle',
            name='option_code',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
