# Generated by Django 4.2.6 on 2023-10-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_productoptiontitle_option_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoptions',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productoptions',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productoptiontitle',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productoptiontitle',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productoptiontitle',
            name='option_type',
            field=models.CharField(choices=[('dropdown', 'dropdown'), ('radio inline', 'radio inline')], max_length=100),
        ),
    ]
